### ISSUE TITLE
a lot of sc and error2 in patrol

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#1809]
![image](https://github.com/Thlumyn/clangen/assets/126827015/3a475827-012c-4ba2-b6cf-04e7898657c4)

send out 2 cats on a border patrol. proceed once you get PATROL ID: gen_border_pumpkineyes | SUCCESS: True

scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/subject/CAP
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/subject/CAP
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/subject
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/subject
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/object
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/object
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: PRONOUN/s_c/subject
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: PRONOUN/s_c/subject
scripts.utility - ERROR - utility.py / pronoun_repl / 740 - Failed to find pronoun: VERB/s_c/'re/'s
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 721, in pronoun_repl
    d = cat_pronouns_dict[inner_details[1]][1]
KeyError: 's_c'
Failed to find pronoun: VERB/s_c/'re/'s

**Comment by ZtheCorgi** [comment]
should be fixed with this PR
https://github.com/Thlumyn/clangen/pull/1827
