### ISSUE TITLE
Outside the clan cats causing crashes.

### ISSUE THREAD

**Issue by Foxyboihdhd** [ClanGenOfficial/clangen#2000]
Clicking on a cat outside the clan causes the game to crash. This is far all outside cats - rouges, exiled and lost. 

As far as I know it doesn’t affect dead cats or cats in the clan.

**Comment by Ediquette** [comment]
also had this issue, here's the log:
root - CRITICAL - main.py / log_crash / 122 - Uncaught exception
Traceback (most recent call last):
  File "c:\Users\alitt\OneDrive\Documents\CLANGEN TESTZONE\clangen\main.py", line 362, in <module>
    game.all_screens[game.current_screen].screen_switches()
  File "c:\Users\alitt\OneDrive\Documents\CLANGEN TESTZONE\clangen\scripts\screens\ProfileScreen.py", line 420, in screen_switches
    self.build_profile()
  File "c:\Users\alitt\OneDrive\Documents\CLANGEN TESTZONE\clangen\scripts\screens\ProfileScreen.py", line 511, in build_profile
    self.profile_elements["cat_info_column2"] = UITextBoxTweaked(self.generate_column2(self.the_cat),
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\alitt\OneDrive\Documents\CLANGEN TESTZONE\clangen\scripts\screens\ProfileScreen.py", line 879, in generate_column2
    game.clan.freshkill_pile.add_cat_to_nutrition(the_cat)
  File "c:\Users\alitt\OneDrive\Documents\CLANGEN TESTZONE\clangen\scripts\clan_resources\freshkill.py", line 592, in add_cat_to_nutrition
    max_score = PREY_REQUIREMENT[prey_status] * factor
                ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'kittypet'
