### ISSUE TITLE
crash upon checking history

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2192]
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\GitHub\clangen\main.py", line 311, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 194, in handle_event
    self.toggle_history_tab()
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 989, in toggle_history_tab
    self.update_disabled_buttons_and_text()
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 1896, in update_disabled_buttons_and_text
    self.history_text_box = UITextBoxTweaked(self.get_all_history_text(),
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 1083, in get_all_history_text
    death_history = self.get_death_text()
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 1349, in get_death_text
    text = self.get_text_for_murder_event(event, death)
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\screens\ProfileScreen.py", line 1326, in get_text_for_murder_event
    return event_text_adjust(Cat, event["unrevealed_text"], self.the_cat, Cat.fetch_cat(death["involved"]))
  File "C:\Users\Leafy\Documents\GitHub\clangen\scripts\utility.py", line 992, in event_text_adjust
    if "acc_plural" in text:
TypeError: argument of type 'NoneType' is not iterable

when a warrior murders an apprentice by "assessing their battle skills" and slashing them across the throat, checking the history of the dead apprentice crashes the game

**Comment by Lyricana** [comment]
![image](https://github.com/ClanGenOfficial/clangen/assets/33564238/9d3ee00e-d79d-45a0-afe6-8226647ec008)
I have also had this issue pop up upon the same event happening.  Here is a screenshot of my game before it crashed when I clicked "close."  This error happens every single time this specific apprentice's history tab is opened.
