### ISSUE TITLE
[BUG] Going on Patrol in New Camp Crashes Game?

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#2409]
**Type**: UI

**Describe the bug**
Loaded up a new clan in the new Ruin camp, had two apprentices and their mentors ready to go on a training patrol. Didn't even get to the patrol page, the game simply crashed when I pressed 'go on patrol'. Didn't even get a patrol ID.

**Grade**: 
Game-breaking

**Reproduce**
Unsure honestly.

**Patrol ID + Outcome Print (if applicable)**:
Patrol Leader: Sootstar
Random Cat: Swallowrush
ERROR: in loading faded cat
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen\main.py", line 334, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 962, in on_use
    self.loading_screen_on_use(self.start_patrol_thread, self.open_patrol_event_screen, (700, 500))
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 219, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 191, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 185, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 489, in run_patrol_start
    self.display_text = self.patrol_obj.setup_patrol(self.current_patrol, self.patrol_type)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 65, in setup_patrol
    final_patrols, final_romance_patrols = self.get_possible_patrols(
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 344, in get_possible_patrols
    final_patrols, final_romance_patrols = self.get_filtered_patrols(
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 751, in get_filtered_patrols
    filtered_patrols, romantic_patrols = self._filter_patrols(
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 683, in _filter_patrols
    if not self._check_constraints(patrol):
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 394, in _check_constraints
    if not self._filter_relationship(patrol):
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 425, in _filter_relationship
    siblings = [test_cat.is_sibling(inter_cat) for inter_cat in testing_cats]
  File "C:\Users\x\Downloads\Gen\clangen\scripts\patrol\patrol.py", line 425, in <listcomp>
    siblings = [test_cat.is_sibling(inter_cat) for inter_cat in testing_cats]
  File "C:\Users\x\Downloads\Gen\clangen\scripts\cat\cats.py", line 1771, in is_sibling
    self.inheritance = Inheritance(self)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\cat_relations\inheritance.py", line 52, in __init__
    self.update_inheritance()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\cat_relations\inheritance.py", line 104, in update_inheritance
    self.init_cousins(inter_id, inter_cat)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\cat_relations\inheritance.py", line 554, in init_cousins
    parent_cats_names = [str(c.name) for c in parents_cats]
  File "C:\Users\x\Downloads\Gen\clangen\scripts\cat_relations\inheritance.py", line 554, in <listcomp>
    parent_cats_names = [str(c.name) for c in parents_cats]
AttributeError: 'NoneType' object has no attribute 'name'

**Commit # or Game Version Number**: 
e7af2cec857d91d736c8657af8094f3f55782113

**Comment by j-gynn** [comment]
I think this should be fixed by the PR that literally just went in, but I'm going to double-check.

**Comment by j-gynn** [comment]
I can't recreate it on the latest version of development now, so I'm hoping it's all good.
