### ISSUE TITLE
[BUG] Season button closing the game

### ISSUE THREAD

**Issue by Hazitos** [ClanGenOfficial/clangen#2686]
**Type**:

- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
The game instantly closes if you click on the season button.

**Grade**: 

- Non-vital - This bug can easily be ignored and does not have a large impact on play

**Reproduce**
1. Go to the clearing
2. Click on the season button in the top left.
3. See error

**Commit # or Game Version Number**:  Dev build 6f64ccdd

**Comment by archanyhm** [comment]
```
root - CRITICAL - main.py / log_crash / 115 - Uncaught exception
Traceback (most recent call last):
  File "main.py", line 337, in <module>
  File "scripts/screens/ClanScreen.py", line 77, in handle_event
  File "scripts/screens/Screens.py", line 404, in menu_button_pressed
KeyError: 'mns open'
Traceback (most recent call last):
  File "main.py", line 337, in <module>
  File "scripts/screens/ClanScreen.py", line 77, in handle_event
  File "scripts/screens/Screens.py", line 404, in menu_button_pressed
KeyError: 'mns open'
```
