### ISSUE TITLE
[BUG] crash upon clicking a new cat's profile

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2749]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
when i tried to click on a cat's name in a new-cat event, the game crashed

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. moon skip till you get an event where a new outsider is generated
2. try to click their name

**Commit # or Game Version Number**: 0b02117fd6160ebff06246855d6ae9213b08f511

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 384, in <module>
    game.all_screens[game.current_screen].screen_switches()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\ProfileScreen.py", line 518, in screen_switches
    self.build_profile()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\ProfileScreen.py", line 722, in build_profile
    ) = self.the_cat.determine_next_and_previous_cats()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat\cats.py", line 3438, in determine_next_and_previous_cats
    idx = sorted_specific_list.index(self)
ValueError: CAT OBJECT:8 is not in list

**Screenshots**

https://github.com/user-attachments/assets/e6799982-642f-43c1-822f-304a200b9b6d

**Comment by j-gynn** [comment]
\*uh-oh\*
that's on me. Lemme fix that rq.
