### ISSUE TITLE
[BUG] Patrols don't work!!

### ISSUE THREAD

**Issue by A-Bright-Guiding-Light** [ClanGenOfficial/clangen#2823]
Like the title says, the patrols don't work! I believe this is because of the new dev update/bug fix? I cannot provide a screenshot as it closes too fast for me to do so! I go to patrols, put a cat on a patrol hit the 'go on patrol' button thing, and it closes!

**Comment by DeadGirlRisen** [comment]
Crash Information for those looking into the issue:

Traceback (most recent call last):
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\screens\PatrolScreen.py", line 1322, in on_use
    self.loading_screen_on_use(
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\screens\PatrolScreen.py", line 715, in run_patrol_start
    self.display_text = self.patrol_obj.setup_patrol(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\patrol\patrol.py", line 102, in setup_patrol
    return self.process_text(self.patrol_event.intro_text, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\deadg\OneDrive\Documents\GitHub\clangen\scripts\patrol\patrol.py", line 1074, in process_text
    text, senses, list_type = find_special_list_types(text)
    ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)

**Comment by Kessekiplayz** [comment]
I too am having this issue!

**Comment by archanyhm** [comment]
Fixed in #2824
