### ISSUE TITLE
[BUG] crash upon auto assigning deputy

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2871]
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 
- Sprite - an issue with the art in the game
- Code - general bugs related to how the game runs and responds to you. 
- Typo - misspellings or incorrect grammar - IMPORTANT: this type of "bugs" are collected here: https://github.com/ClanGenOfficial/clangen/issues/1818

**Describe the bug**
rare(?) bug that causes the game to crash. looks like it has to do with deputy personality. i have "let leaders choose deputies automatically" on

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent

**Reproduce**
1. turn "let leaders appoint deputies automatically" on
1. everyone's favorite. moon skip and pray

**Commit # or Game Version Number**: 2ca0666816f2d35806c52e3b84125cf4d0379b89

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1183, in one_moon_cat
    self.perform_ceremonies(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1360, in perform_ceremonies
    if game.clan.deputy.personality.trait == "bloodthirsty":
AttributeError: 'NoneType' object has no attribute 'personality'

**Comment by j-gynn** [comment]
how in the...? sel, were you rapidly spam-clicking timeskips here? 

The only thing I can think of that could cause this is this insanely-specific sequence of events:
1. you timeskip and the leader dies
2. the code checking if the deputy exists is passed
3. meanwhile, whilst that code is running, you timeskip again and the deputy dies
4. now there is no deputy and the game crashes

**Comment by selkirks** [comment]
> how in the...? sel, were you rapidly spam-clicking timeskips here? 
> 
> 
> 
> The only thing I can think of that could cause this is this insanely-specific sequence of events:
> 
> 1. you timeskip and the leader dies
> 
> 2. the code checking if the deputy exists is passed
> 
> 3. meanwhile, whilst that code is running, you timeskip again and the deputy dies
> 
> 4. now there is no deputy and the game crashes

yaaaaa fast time skippy

**Comment by j-gynn** [comment]
Looks like this is just a race condition wearing a different hat. Duplicate of #2844

**Comment by j-gynn** [comment]
I have a sneaking suspicion all of these reports are likely the same
