### ISSUE TITLE
[BUG] crash when inviting former clancat in

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2887]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
when trying to invite in a former clancat, the game crashes

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent
- 
**Reproduce**
1. go on patrols/meet outsiders in events till one has a former clancat backstory
2. try to invite them in

**Commit # or Game Version Number**: 514e67389154242c58221ad04d1eef06098ff8ff

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 140, in one_moon
    self.handle_lead_den_event()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 366, in handle_lead_den_event
    chosen_event = random.choice(events)
  File "C:\Users\Leafy\AppData\Local\Programs\Thonny\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

**Comment by tobes03** [comment]
I'm fairly sure this is because all of our leader's den outsiders interactions only account for lost/exiled/rogue/loner/kittypet type backstories. We'll have to write some for clancats

Edit: Nope, that was not the entirety of the problem
