### ISSUE TITLE
[BUG] Game crashes when pressing "change name"

### ISSUE THREAD

**Issue by LaurelWillow** [ClanGenOfficial/clangen#3030]
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
When pressing the "change name" button on a cat's profile, the game crashes with this error: 

root - CRITICAL - main.py / log_crash / 118 - Uncaught exception
Traceback (most recent call last):
  File "main.py", line 302, in <module>
  File "scripts/screens/ProfileScreen.py", line 247, in handle_event
  File "scripts/screens/ProfileScreen.py", line 292, in handle_tab_events
  File "scripts/game_structure/windows.py", line 556, in __init__
AttributeError: 'Name' object has no attribute 'status'
Traceback (most recent call last):
  File "main.py", line 302, in <module>
  File "scripts/screens/ProfileScreen.py", line 247, in handle_event
  File "scripts/screens/ProfileScreen.py", line 292, in handle_tab_events
  File "scripts/game_structure/windows.py", line 556, in __init__
AttributeError: 'Name' object has no attribute 'status'

**Grade**: (only select one)
- Game-breaking - a bug that makes it impossible to play the game

**Reproduce**
Press the "change name" button on a cat's profile. 
The leader and deputy's names can still be changed as normal, they do not crash for whatever reason. 
All other roles crash the game. 
Cats outside the clan crash the game too. 
Cats in StarClan and the Unknown Residence crash the game as well. This includes the StarClan guide. 

If you change a cat's role and then press change name, it will not crash. 

Yes, I did just crash my game many times in a row to figure all this out. 

**Commit # or Game Version Number**: 
b8bb076d

**Additional context**
Originally reported by ColettewithRose on Discord. 

My best guess is the role/status of a cat is not being assigned properly, somehow? Maybe being a leader or deputy, a role where you can only have one at a time, will assign that. Or if you change the role of a cat, it will assign the new role. So in those cases it won't crash. 
That's my guess as someone who is not a coder though. Take with a hefty grain of salt.

**Comment by LaurelWillow** [comment]
This got fixed by Scribble as I was reporting it lol. Good job scribble, we can close this issue now
