### ISSUE TITLE
[BUG] Game tried to add a new cat to the clan and crashed

### ISSUE THREAD

**Issue by sketchywyvern** [ClanGenOfficial/clangen#3089]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

Traceback (most recent call last):
  File "main.py", line 299, in <module>
  File "scripts\screens\EventsScreen.py", line 722, in on_use
  File "scripts\screens\Screens.py", line 150, in loading_screen_on_use
  File "scripts\game_structure\propagating_thread.py", line 25, in join
  File "scripts\game_structure\propagating_thread.py", line 18, in run
  File "scripts\screens\Screens.py", line 117, in _work_target
  File "scripts\screens\Screens.py", line 111, in _work_target
  File "scripts\events.py", line 137, in one_moon
  File "scripts\events.py", line 1205, in one_moon_cat
  File "scripts\events.py", line 2078, in invite_new_cats
  File "scripts\events_module\handle_short_events.py", line 192, in handle_event
  File "scripts\events_module\handle_short_events.py", line 322, in handle_new_cats
  File "scripts\utility.py", line 508, in create_new_cat_block
  File "random.py", line 290, in choice
IndexError: Cannot choose from an empty sequence

### Grade

Important - The bug has a large effect on the gameplay but is not urgent

### Steps to reproduce the behavior

Unsure. Happens on moon transition

### Commit # or Game Version Number

0.12.1

**Comment by scribblecrumb** [comment]
What biome, camp, and season were you in when it crashed?
