### ISSUE TITLE
[BUG] Cannot open game after update (Note: fixed myself, ignore)

### ISSUE THREAD

**Issue by EmTheAnxiousDragon** [ClanGenOfficial/clangen#3150]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

After I updated the game, I had to fight with my antivirus to allow the game to run and not be flagged as a virus. However, now that this is done, this error appears:

Traceback (most recent call last):
  File "main.py", line 158, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scripts\game_structure\audio.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pygame\__init__.py", line 39, in <module>
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ebook\\OneDrive\\Desktop\\Games\\Clangen\\_internal\\pygame'

It seems like my antivirus deleted some sort of file? I am unsure what to do about this or what the best fix would be.

### Grade

Game-breaking - a bug that makes it impossible to play the game

### Steps to reproduce the behavior

1. Go to the Clangen application
2. Open the application

### Patrol ID + Outcome Print (if applicable)

Traceback (most recent call last):
  File "main.py", line 158, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scripts\game_structure\audio.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pygame\__init__.py", line 39, in <module>
  File "<frozen os>", line 1119, in add_dll_directory
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\ebook\\OneDrive\\Desktop\\Games\\Clangen\\_internal\\pygame'

### Commit # or Game Version Number

12.2

**Comment by archanyhm** [comment]
Not a bug.
