### ISSUE TITLE
[BUG] game crashes upon opening

### ISSUE THREAD

**Issue by rustykitty** [ClanGenOfficial/clangen#3261]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

full output from PyCharm:

```python
/Users/rusty/coding/clangen/.venv/bin/python main.py 
Running on source code
Version Name:  0.9.0
Running on commit 6516190e7a865b5fe5fbd11bc484d8e2f59f688c
pygame-ce 2.5.2 (SDL 2.30.8, Python 3.12.7)
root - CRITICAL - main.py / log_crash / 118 - Uncaught exception
Traceback (most recent call last):
  File "/Users/rusty/coding/clangen/main.py", line 201, in <module>
    from scripts.screens.all_screens import AllScreens
  File "/Users/rusty/coding/clangen/scripts/screens/all_screens.py", line 1, in <module>
    from .AllegiancesScreen import AllegiancesScreen
  File "/Users/rusty/coding/clangen/scripts/screens/AllegiancesScreen.py", line 16, in <module>
    from .Screens import Screens
  File "/Users/rusty/coding/clangen/scripts/screens/Screens.py", line 10, in <module>
    import scripts.screens.screens_core.screens_core
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/__init__.py", line 1, in <module>
    from scripts.screens.screens_core import screens_core
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/screens_core.py", line 562, in <module>
    rebuild_core()
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/screens_core.py", line 69, in rebuild_core
    menu_buttons["catlist_screen"] = UISurfaceImageButton(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/game_structure/ui_elements.py", line 103, in __init__
    super().__init__(
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 150, in __init__
    self.rebuild_from_changed_theme_data()
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 666, in rebuild_from_changed_theme_data
    self.rebuild()
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 738, in rebuild
    'text': translate(self.text, **self.text_kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/game_structure/monkeypatch.py", line 36, in translate
    return event_text_adjust(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/utility.py", line 2119, in event_text_adjust
    text, senses, list_type, cat_tag = find_special_list_types(text)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/utility.py", line 1977, in find_special_list_types
    text = text.replace(list_text, list_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not None
Traceback (most recent call last):
  File "/Users/rusty/coding/clangen/main.py", line 201, in <module>
    from scripts.screens.all_screens import AllScreens
  File "/Users/rusty/coding/clangen/scripts/screens/all_screens.py", line 1, in <module>
    from .AllegiancesScreen import AllegiancesScreen
  File "/Users/rusty/coding/clangen/scripts/screens/AllegiancesScreen.py", line 16, in <module>
    from .Screens import Screens
  File "/Users/rusty/coding/clangen/scripts/screens/Screens.py", line 10, in <module>
    import scripts.screens.screens_core.screens_core
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/__init__.py", line 1, in <module>
    from scripts.screens.screens_core import screens_core
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/screens_core.py", line 562, in <module>
    rebuild_core()
  File "/Users/rusty/coding/clangen/scripts/screens/screens_core/screens_core.py", line 69, in rebuild_core
    menu_buttons["catlist_screen"] = UISurfaceImageButton(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/game_structure/ui_elements.py", line 103, in __init__
    super().__init__(
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 150, in __init__
    self.rebuild_from_changed_theme_data()
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 666, in rebuild_from_changed_theme_data
    self.rebuild()
  File "/Users/rusty/coding/clangen/.venv/lib/python3.12/site-packages/pygame_gui/elements/ui_button.py", line 738, in rebuild
    'text': translate(self.text, **self.text_kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/game_structure/monkeypatch.py", line 36, in translate
    return event_text_adjust(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/utility.py", line 2119, in event_text_adjust
    text, senses, list_type, cat_tag = find_special_list_types(text)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rusty/coding/clangen/scripts/utility.py", line 1977, in find_special_list_types
    text = text.replace(list_text, list_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not None

Process finished with exit code 1

```

### Grade

Game-breaking - a bug that makes it impossible to play the game

### Steps to reproduce the behavior

open the game

### Patrol ID + Outcome Print (if applicable)

N/A

### Commit # or Game Version Number

https://github.com/ClanGenOfficial/clangen/commit/6516190e7a865b5fe5fbd11bc484d8e2f59f688c

### Additional context

I suspect that the UI localization branch merge broke a lot of stuff including #3259

**Comment by j-gynn** [comment]
Unable to replicate, but it's possible this is because I was the developer of localization.
