### ISSUE TITLE
[BUG] Save on fullscreen, game crashes on next open

### ISSUE THREAD

**Issue by bakermor** [ClanGenOfficial/clangen#3284]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

When I save the game in fullscreen mode it crashes the next time I open it.

### Grade

Game-breaking - a bug that makes it impossible to play the game

### Steps to reproduce the behavior

Fullscreen your game
Quit
Start the game again

### Commit # or Game Version Number

eab5da10c3ca4518b1442035cbab914a454606c5

### Additional context

Looks like it's probably just that read_config.read() should be read_config

![image](https://github.com/user-attachments/assets/ba913f37-16fa-4248-b4b8-c1170c0556b7)

### Screenshots

Traceback (most recent call last):
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\main.py", line 158, in <module>
    from scripts.game_structure.monkeypatch import translate
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\game_structure\monkeypatch.py", line 3, in <module>
    from scripts.cat.cats import Cat
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\cat\cats.py", line 18, in <module>
    from scripts.cat.history import History
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\cat\history.py", line 4, in <module>
    from scripts.game_structure.game_essentials import game
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\game_structure\game_essentials.py", line 627, in <module>
    toggle_fullscreen(
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\game_structure\screen_settings.py", line 275, in toggle_fullscreen
    set_display_mode(
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\game_structure\screen_settings.py", line 84, in set_display_mode
    determine_screen_scale(display_size[0], display_size[1], ingame_switch)
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\game_structure\screen_settings.py", line 222, in determine_screen_scale
    screen_config = ujson.load(read_config.read())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected file

**Comment by j-gynn** [comment]
i forgor an `s`
