### ISSUE TITLE
[BUG] Game Crashes clicking Medicine Cat Den 

### ISSUE THREAD

**Issue by bakermor** [ClanGenOfficial/clangen#3287]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

My only medicine cat was injured and clicking on the medicine cat den crashed the game

### Grade

Regular - A typical bug that should be seen to soon, but doesn't necessarily break the game or inhibit the player

### Steps to reproduce the behavior

Have all your medicine cats be injured
Click on medicine cat den

### Commit # or Game Version Number

8e1979e81e2179c42f32acde802b6d8b91205ea5

### Screenshots

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.5\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2023.2.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\main.py", line 396, in <module>
    game.all_screens[game.current_screen].screen_switches()
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\screens\MedDenScreen.py", line 377, in screen_switches
    event_text_adjust(Cat, "<br>".join(med_messages))
  File "C:\Users\mbake\Documents B\ClanGen\ClanGen\clangen\scripts\utility.py", line 2222, in event_text_adjust
    med = choice(get_alive_status_cats(Cat, ["medicine cat"], working=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbake\AppData\Local\Programs\Python\Python312\Lib\random.py", line 347, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

**Comment by j-gynn** [comment]
Should be fixed incidentally by #3136
