### ISSUE TITLE
[BUG] Game Crashes on Some Patrols

### ISSUE THREAD

**Issue by thunderingboom** [ClanGenOfficial/clangen#3298]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

On some patrols for whatever reason the game will crash when you press 'start patrol'. It is not every time, but happens with random cats and I have had it happen with multiple cats on patrol (such as mentor and apprentice).

### Grade

Dire - Still playable, but a major feature is broken

### Steps to reproduce the behavior

1. Patrol until game crashes

### Patrol ID + Outcome Print (if applicable)

root - CRITICAL - main.py / log_crash / 118 - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen\main.py", line 331, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 1399, in on_use
    self.loading_screen_on_use(
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 178, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 145, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 139, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 776, in run_patrol_start
    self.display_text = self.patrol_obj.setup_patrol(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 88, in setup_patrol
    final_patrols, final_romance_patrols = self.get_possible_patrols(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 392, in get_possible_patrols
    possible_patrols.extend(self.generate_patrol_events(self.DISASTER))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 653, in generate_patrol_events
    for patrol in patrol_dict:
                  ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\x\Downloads\Gen\clangen\main.py", line 331, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 1399, in on_use
    self.loading_screen_on_use(
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 178, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\x\Downloads\Gen\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 145, in _work_target
    raise exp
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\Screens.py", line 139, in _work_target
    target(*args)
  File "C:\Users\x\Downloads\Gen\clangen\scripts\screens\PatrolScreen.py", line 776, in run_patrol_start
    self.display_text = self.patrol_obj.setup_patrol(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 88, in setup_patrol
    final_patrols, final_romance_patrols = self.get_possible_patrols(
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 392, in get_possible_patrols
    possible_patrols.extend(self.generate_patrol_events(self.DISASTER))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\Downloads\Gen\clangen\scripts\events_module\patrol\patrol.py", line 653, in generate_patrol_events
    for patrol in patrol_dict:
                  ^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

### Commit # or Game Version Number

8e1979e81e2179c42f32acde802b6d8b91205ea5

**Comment by thunderingboom** [comment]
There is no patrol ID because the game doesn't even get to the patrol before it crashes!

**Comment by Tiritirimatangi** [comment]
![image](https://github.com/user-attachments/assets/1c08bb0e-b59d-47dd-9710-5c9fbdd6f4c5)
Okay so this is the med patrol that keeps crashing, and the error message associated is: 
Traceback (most recent call last):
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/main.py", line 331, in <module>
    game.all_screens[game.current_screen].on_use()
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/screens/PatrolScreen.py", line 1402, in on_use
    self.loading_screen_on_use(
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/screens/Screens.py", line 178, in loading_screen_on_use
    work_thread.join()
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/game_structure/propagating_thread.py", line 25, in join
    raise self.exc
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/game_structure/propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/screens/Screens.py", line 145, in _work_target
    raise exp
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/screens/Screens.py", line 139, in _work_target
    target(*args)
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/screens/PatrolScreen.py", line 934, in run_patrol_proceed
    ) = self.patrol_obj.proceed_patrol("proceed")
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/events_module/patrol/patrol.py", line 142, in proceed_patrol
    return self.determine_outcome(antagonize=(path == "antag"))
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/events_module/patrol/patrol.py", line 726, in determine_outcome
    return final_event.execute_outcome(self)
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/events_module/patrol/patrol_outcome.py", line 218, in execute_outcome
    results = [self._handle_new_cats(patrol)]
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/events_module/patrol/patrol_outcome.py", line 844, in _handle_new_cats
    cats=adjust_list_text(type_list),
  File "/Users/hawma085/Documents/GitHub/clangen-FOX/scripts/utility.py", line 1841, in adjust_list_text
    item1 = ", ".join(list_of_items[:-1])
TypeError: sequence item 0: expected str instance, Name found

**Comment by j-gynn** [comment]
Oh, for the love of- stupid Name class!

**Comment by j-gynn** [comment]
Actually @Tiritirimatangi that looks like a different bug to thunderingboom's bug, could you pop that in its own PR

**Comment by j-gynn** [comment]
nvm fixed it
