### ISSUE TITLE
[BUG] game crashes when saving

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#3304]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

the game crashes whenever you skip a moon and try to save

### Grade

Dire - Still playable, but a major feature is broken

### Steps to reproduce the behavior

1. make a new clan
2. save on moon 0
3. moon skip
4. save on moon 1
5. game crashes

### Commit # or Game Version Number

187eae88d7dc2ddc1587a94022c9bb45ad6a7800

### Additional context

[stderr_20241230_185010.log](https://github.com/user-attachments/files/18278941/stderr_20241230_185010.log)

**Comment by selkirks** [comment]
log url wont work on my end? 

heres the text version
Traceback (most recent call last):
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\main.py", line 341, in <module>
    game.all_screens[game.current_screen].handle_event(event)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\screens\ClanScreen.py", line 65, in handle_event
    game.save_events()
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\game_structure\game_essentials.py", line 516, in save_events
    game.safe_save(f"{get_save_dir()}/{game.clan.name}/events.json", events_list)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\game_structure\game_essentials.py", line 223, in safe_save
    _data = ujson.dumps(write_data, indent=4)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CAT OBJECT:9 is not JSON serializable

**Comment by scribblecrumb** [comment]
Fixed
