### ISSUE TITLE
[BUG] random crash while skipping a moon

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#3307]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

whilst skipping a moon (not speed-skipping), the game crashed

### Grade

Important - The bug has a large effect on the gameplay but is not urgent

### Steps to reproduce the behavior

1. make a clan
2. skip moons (slowly) till error occurs

### Commit # or Game Version Number

187eae88d7dc2ddc1587a94022c9bb45ad6a7800

### Additional context

AttributeError: 'UIVerticalScrollBar' object has no attribute '_container_to_scroll'
Traceback (most recent call last):
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\main.py", line 388, in <module>
    MANAGER.process_events(event)
  File "C:\Users\Leafy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\clangen-08OgdQ_r-py3.11\Lib\site-packages\pygame_gui\ui_manager.py", line 240, in process_events
    consumed_event = ui_element.process_event(event)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\clangen-08OgdQ_r-py3.11\Lib\site-packages\pygame_gui\elements\ui_vertical_scroll_bar.py", line 267, in process_event
    self._check_should_handle_mousewheel_event() and
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\clangen-08OgdQ_r-py3.11\Lib\site-packages\pygame_gui\elements\ui_vertical_scroll_bar.py", line 291, in _check_should_handle_mousewheel_event
    if self._container_to_scroll and self._container_to_scroll.are_contents_hovered():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UIVerticalScrollBar' object has no attribute '_container_to_scroll'

**Comment by scribblecrumb** [comment]
Hm, I can't seem to trigger this again.  It's possible it got fixed by the changes to our ui_element classes.  Please report again if it's still occurring!
