### ISSUE TITLE
[BUG] herb-related crash upon skipping a moon

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#3308]
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

rarely, the game crashes on moon skip due to an herb issue. my clan is on classic mode if that helps, no warriors den focus

### Grade

Important - The bug has a large effect on the gameplay but is not urgent

### Steps to reproduce the behavior

1. make a classic clan
2. moon skip

### Commit # or Game Version Number

187eae88d7dc2ddc1587a94022c9bb45ad6a7800

### Additional context

Traceback (most recent call last):
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\main.py", line 331, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\screens\EventsScreen.py", line 722, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\screens\Screens.py", line 178, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\screens\Screens.py", line 145, in _work_target
    raise exp
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\screens\Screens.py", line 139, in _work_target
    target(*args)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\events.py", line 142, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\events.py", line 1168, in one_moon_cat
    self.other_interactions(cat)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\events.py", line 2033, in other_interactions
    handle_short_events.handle_event(
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\events_module\short\handle_short_events.py", line 281, in handle_event
    self.handle_herb_supply(block)
  File "C:\Users\Leafy\OneDrive\Documents\clangen stuff\clangen\scripts\events_module\short\handle_short_events.py", line 835, in handle_herb_supply
    self.chosen_herb = random.choice(possible_herbs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\random.py", line 373, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

**Comment by scribblecrumb** [comment]
Might be fixed after my Herb PR
