### ISSUE TITLE
error codes and issue with ujson?

### ISSUE THREAD

**Issue by lumberpickle** [ClanGenOfficial/clangen#389]
i tried to play the updated version of clan gen experimental, updated ujson and got pygame-gui but i kept coming with this error code

>
ImportError: DLL load failed while importing ujson: The specified module could not be found.
>>> 

i tried the main version and a god a lot more errors with it

>>> %Run main.py
pygame 2.1.2 (SDL 2.0.18, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\darke\Downloads\clangen-main_unused\clangen-main_unused\main.py", line 6, in <module>
    from scripts.screens import *
  File "C:\Users\darke\Downloads\clangen-main_unused\clangen-main_unused\scripts\screens.py", line 3, in <module>
    from .clan import *
  File "C:\Users\darke\Downloads\clangen-main_unused\clangen-main_unused\scripts\clan.py", line 1, in <module>
    from .cats import *
  File "C:\Users\darke\Downloads\clangen-main_unused\clangen-main_unused\scripts\cats.py", line 10, in <module>
    import ujson
ImportError: DLL load failed while importing ujson: The specified module could not be found.
>>> 

whats going wrong? how do i fix it? my girlfirend sitting beside me could get it working on hers but we couldnt figure out mine.

**Comment by ThriftFoot** [comment]
ive had that error too, but with pygame_gui instead

**Comment by Ryos00** [comment]
There's been a fallback implemented for json if ujson does not work.
